version: "3"

networks:
  demo:

services:
  client: 
    image: 
    restart: 
    environment: 
      HOST: 
      PORT: 
    networks:
      - demo
  server:
    image: 
    restart: 
    ports:
      - 
    networks:
      - demo