version: "3"

networks:
  demo:

services:
  client: 
    image: "client:foo"
    restart: always
    environment: 
      HOST: server
      PORT: 3000
    networks:
      - demo
  server:
    image: "server:foo"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - demo